# Generated by Django 4.1.6 on 2023-02-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255, unique=True)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, unique=True)),
                ('apellidoss', models.CharField(max_length=255, unique=True)),
                ('carnet_identidad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.curso')),
            ],
        ),
        migrations.CreateModel(
            name='NotasMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trabajo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disponible', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=255, unique=True)),
                ('docente', models.CharField(max_length=255, unique=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.curso')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.materia'),
        ),
    ]
